.PHONY: clean All

All:
	@echo "----------Building project:[ CLTool - Debug ]----------"
	@$(MAKE) -f  "CLTool.mk"
clean:
	@echo "----------Cleaning project:[ CLTool - Debug ]----------"
	@$(MAKE) -f  "CLTool.mk" clean
