Header header

float32[3] BaseLLA 			# base position in lat-lon-altitude (deg, deg, m)
uint32 cycle_slip_count 	# number of cycle slips detected
uint32 roverObs				# number of observations from rover (GPS, Glonass, Gallileo, Beidou, Qzs)
uint32 baseObs				# number of observations from base (GPS, Glonass, Gallileo, Beidou, Qzs)
uint32 roverEph				# number of ephemeris messages from rover (GPS, Glonass, Gallileo, Beidou, Qzs)
uint32 baseEph				# number of ephemeris messages from rover (GPS, Glonass, Gallileo, Beidou, Qzs)
uint32 baseAntcount			# number of base station antenna position measurements

